PetShopToys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('about/', views.about, name='about'),  
    path('contact/', views.contact, name='contact'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('allauth.urls')),  
    
    # Custom user authentication for both authentication systems (Django and Django-allauth)
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path, include
from . import views

app_name = 'payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('create-stripe-checkout-session/', views.create_stripe_checkout_session, name='create_stripe_checkout_session'),
    path('success/', views.success, name='success'),
    path('cancel/', views.cancel, name='cancel'),
    path('test/', views.test, name='test'),
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

shop/urls.py
# shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),  # Root shop URL
    path('products/', views.product_list, name='products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('products/search/', views.search_products, name='search_products'),
    path('cats/', views.product_list, {'pet_type_slug': 'cats'}, name='cats_products'),
    path('dogs/', views.product_list, {'pet_type_slug': 'dogs'}, name='dogs_products'),
    path('<slug:pet_type_slug>/', views.product_list, name='product_list_by_pet_type'),
    path('<slug:pet_type_slug>/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

PetShopToys/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

PetShopToys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

#login specific
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CreateUserForm
from django.contrib import messages

# Create your views here.

def home(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def payment(request):
    return render(request, 'checkout.html')

# login and out specific

def registerPage(request):
    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account was created for ' + user.username)
            return redirect('login')
        
    context = {'form': form}
    return render(request, 'register.html', context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Invalid username or password')

    context = {}
    return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login.html') 

PetShopToys/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
        <div class="text-center">
        <h1>About Us</h1>
        <div class="alert alert-info" role="alert">
            We are committed to delivering the best pet products with care and quality!
        </div>
        <p>We are a passionate team dedicated to providing the best toys and accessories for your pets!</p>
    </div>

    <div class="d-flex justify-content-center mt-4">
        <!-- Card for Our Mission -->
        <div class="card" style="width: 18rem; margin: 0 15px;">
            <div class="card-body d-flex flex-column">
                <h5 class="card-title text-center"><i class="fas fa-paw"></i> Our Mission</h5>
                <p class="card-text text-justify">
                    Our mission is to bring joy to your pets by offering high-quality and innovative toys. 
                    We aim to create a safe and fun environment for your pets, so they can thrive and enjoy every moment.
                </p>
            </div>
        </div>

        <!-- Card for Our Values -->
        <div class="card" style="width: 18rem; margin: 0 15px;">
            <div class="card-body d-flex flex-column">
                
                <h5 class="card-title text-center"><i class="fas fa-paw"></i>Our Values</h5>
                <p class="card-text text-justify">
                    We believe in sustainability, compassion, and customer satisfaction. Our products are carefully selected to ensure your pets get the best, while also being environmentally friendly.
                </p>
            </div>
        </div>
    </div>

    <div class="text-center mt-5">
        <a href="{% url 'contact' %}" class="btn btn-primary">Contact Us</a>
    </div>    
{% endblock %}

PetShopToys/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pet Shop Toys</title>

    {% load static %}
    {% load account %}
    {% url 'account_login' as login_url %}
    {% url 'account_signup' as signup_url %}
    {% url 'account_logout' as logout_url %}
    {% url 'cart:cart_detail' as cart_url %}

    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'css/favicon_io/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'css/favicon_io/favicon-16x16.png' %}"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'css/favicon_io/apple-touch-icon.png' %}"
    />
    <!-- <link rel="manifest" href="{% static 'css/favicon_io/site.webmanifest' %}"> -->

    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/styles.css' %}"
    />

    <style>
      .navbar {
        padding: 10px 0;
        top: 0;
        width: 100%;
        z-index: 1000;
      }

      .container {
        margin-top: 5px;
      }

      footer {
        margin-top: auto;
        width: 100%;
        background-color: #343a40;
        color: white;
        padding: 1rem;
        text-align: center;
      }

      body {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
      }

      .content-wrapper {
        padding-bottom: 80px;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-1">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Pet Shop Toys</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shop:products' %}">All Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'payment:cart_detail' %}">
                <i class="fas fa-shopping-cart"></i>
                <span class="badge bg-primary" id="cart-count">
                  {% if cart_items_count %}{{ cart_items_count }}{% else %}0{% endif %}
                </span>
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <span class="nav-link">Welcome, {{ user.username }}</span>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    

    <div class="content-wrapper">
      <div class="container mt-4">{% block content %} {% endblock %}</div>
    </div>

    <footer>
      <p class="mb-2">Connect with our team on GitHub:</p>
      <div class="d-flex justify-content-center">
        <a
          href="https://github.com/alice173"
          target="_blank"
          class="mx-2 text-light"
        >
          <i class="fab fa-github"></i> Alice Mahtani
        </a>
        <a
          href="https://github.com/BenWilliams89"
          target="_blank"
          class="mx-2 text-light"
        >
          <i class="fab fa-github"></i> Ben Williams
        </a>
        <a
          href="https://github.com/Navya-K-N-24"
          target="_blank"
          class="mx-2 text-light"
        >
          <i class="fab fa-github"></i> Navya Keelara Nagaraju
        </a>
        <a
          href="https://github.com/NikoAtillio"
          target="_blank"
          class="mx-2 text-light"
        >
          <i class="fab fa-github"></i> Nikos Norman
        </a>
        <a
          href="https://github.com/Samersetred"
          target="_blank"
          class="mx-2 text-light"
        >
          <i class="fab fa-github"></i> Somerset Dromgoole
        </a>
      </div>
    </footer>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          document.querySelectorAll('.add-to-cart').forEach(function(button) {
              button.addEventListener('click', function(event) {
                  event.preventDefault();
                  var productId = this.dataset.productId;
                  var url = this.href;
  
                  fetch(url, {
                      method: 'POST',
                      headers: {
                          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                          'Content-Type': 'application/json'
                      },
                      body: JSON.stringify({ product_id: productId })
                  })
                  .then(response => response.json())
                  .then(data => {
                      document.getElementById('cart-count').textContent = data.cart_items_count;
                  });
              });
          });
      });
  </script>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

PetShopToys/templates/contact.html
{% extends 'base.html' %}

{% block content %}
        <div class="container mt-5">
            <div class="card p-4 shadow-sm">
                <h3 class="text-center">Get in Touch</h3>
                <p class="text-center">Have questions? We'd love to hear from you!</p>
    
                <form method="post" action="{% url 'contact' %}">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="name" class="form-label">Your Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="email" class="form-label">Your Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
    
                    <div class="mb-3">
                        <label for="message" class="form-label">Your Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                    </div>
    
                    <button type="submit" class="btn btn-primary w-100">Send Message</button>
                </form>
            </div>
        </div>

{% endblock %}

PetShopToys/templates/index.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<div class="text-center">
  <h1>Welcome to Pet Shop Toys!</h1>
  <p>Find the best for your pets!</p>
  <a href="{% url 'shop:products' %}" class="btn btn-primary">Shop All Products</a>
</div>

<div class="d-flex justify-content-center mt-4">
  <!-- Card for Cats -->
  <div class="card" style="width: 18rem; margin: 0 15px">
    <img
      src="{% static 'images/main_cat.jpg' %}"
      class="card-img-top"
      alt="Cats"
    />
    <div class="card-body">
      <h5 class="card-title">Shop for Cats</h5>
      <p class="card-text">
        Find the best toys and accessories for your feline friends!
      </p>
      <a
        href="{% url 'shop:product_list_by_pet_type' 'cats' %}"
        class="btn btn-primary"
        >Shop Now</a
      >
    </div>
  </div>

  <!-- Card for Dogs -->
  <div class="card" style="width: 18rem; margin: 0 15px">
    <img
      src="{% static 'images/main_dog.jpg' %}"
      class="card-img-top"
      alt="Dogs"
    />
    <div class="card-body">
      <h5 class="card-title">Shop for Dogs</h5>
      <p class="card-text">
        Discover toys and accessories for your loyal companions!
      </p>
      <a
        href="{% url 'shop:product_list_by_pet_type' 'dogs' %}"
        class="btn btn-primary"
        >Shop Now</a
      >
    </div>
  </div>
</div>
{% endblock %}

PetShopToys/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% block content %}

<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #f0f0f0 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: rgba(255, 255, 255, 0.7);
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color:rgb(34, 32, 32) !important;			
		}

		.login_btn {
			width: 100%;
			background:rgb(34, 32, 32) !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background:rgb(34, 32, 32) !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color:rgb(34, 32, 32);
			color: white;
			padding: 20px;
			margin-top: 20px;
		}
	</style>
</head>
<body>
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>
            </div>

			{% for message in messages %}
				<p id="messages">{{message}}</p>
			{% endfor %}

            <div class="mt-4">
                <div class="d-flex justify-content-center links login_container">
                    Don't have an account? <a href="{% url 'register' %}" class="btn login_btn">Register</a>
                </div>
                <div class="d-flex justify-content-center links mt-2 login_container">
                    <a href="{% url 'index' %}" class="btn login_btn">Back to Shop</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

PetShopToys/templates/productscat.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="text-center">
    <h1>Shop for Cats</h1>
    <p>Find the best toys and accessories for your feline friends!</p>
</div>

<!-- List of Cat Accessories -->
<div class="row mt-4">
        <div class="col-md-4">
        <div class="card h-100">
            <!-- Image in Card Header -->
            <img src="{% static 'images/collar_6.png' %}" class="card-img-top" alt="Cat Collar">
            <div class="card-body">
                <h5 class="card-title">Cat Collar 1 - Plaid Cat Collar Grey</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 3.25</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <!-- Image in Card Header -->
            <img src="{% static 'images/collar_5.png' %}" class="card-img-top" alt="Cat Collar">
            <div class="card-body">
                <h5 class="card-title">Cat Collar 2 - Spotty Bow Tie Cat Collar Blue</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 5.00</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/collar_4.png' %}" class="card-img-top" alt="Cat Collar">
            <div class="card-body">
                <h5 class="card-title">Cat Collar 3 - Nylon Cat Collar Red</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 2.50</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_bed2.png' %}" class="card-img-top" alt="Cat Bed">
            <div class="card-body">
                <h5 class="card-title">Cat Bed 1 - Clamshell Cat Bed Blue Spotty</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 11.20</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_bed3.png' %}" class="card-img-top" alt="Cat Bed">
            <div class="card-body">
                <h5 class="card-title">Cat Bed 2 - Igloo Cat Bed Grey Spotty</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 19.00</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_bed4.png' %}" class="card-img-top" alt="Cat Bed">
            <div class="card-body">
                <h5 class="card-title">Cat Bed 3 - Velouria Hooded Cat Bed Brown</h5>
                <p class="card-text">One size</p>
                <p class="card-price">£ 14.00</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_food1.png' %}" class="card-img-top" alt="Cat Food">
            <div class="card-body">
                <h5 class="card-title">Cat Food 1 - Royal Canin Feline Instinctive Adult Wet Cat Food In Gravy</h5>
                <p class="card-text">48 x 85g</p>
                <p class="card-price">£ 36.09</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_food2.png' %}" class="card-img-top" alt="Cat Food">
            <div class="card-body">
                <h5 class="card-title">Cat Food 2 - Royal Canin British Shorthair Adult Dry Cat Food In 10kg</h5>
                <p class="card-text">10kg</p>
                <p class="card-price">£ 78.49</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card h-100">
            <img src="{% static 'images/cat_food3.png' %}" class="card-img-top" alt="Cat Food">
            <div class="card-body">
                <h5 class="card-title">Cat Food 3 - Royal Canin Feline Fit Dry Adult Cat Food 10kg</h5>
                <p class="card-text">10kg</p>
                <p class="card-price">£ 59.49</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

PetShopToys/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block content %}
<html>
<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #f0f0f0 !important; 
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background:rgba(255, 255, 255, 0.7);
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color:rgb(34, 32, 32);
		}
		.login_btn {
			width: 100%;
			background:rgb(34, 32, 32) !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background:rgb(34, 32, 32) !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card" aria-label="User registration card">
                <div class="d-flex justify-content-center" aria-label="Register Account Button">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}

                        <div class="input-group mb-3" aria-label="Username input field">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{ form.username }}
                        </div>
                        <div class="input-group mb-2" aria-label="Email input field">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{ form.email }}
                        </div>
                        <div class="input-group mb-2" aria-label="First password input field">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{ form.password1 }}
                        </div>
                        <div class="input-group mb-2" aria-label="Confirm password input field">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{ form.password2 }}
                        </div>
                        <div class="d-flex justify-content-center mt-3 login_container" aria-label="Submit button">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>
                    </form>
                </div>
                <div class="mt-4">
                    <div class="d-flex justify-content-center links login_container" aria-label="Login link">
                        Already have an account? <a href="{% url 'login' %}" class="btn login_btn">Login</a>
                    </div>

                    {{form.errors}}

                    <div class="d-flex justify-content-center links mt-2 login_container" aria-label="Back to store link">
                        <a href="{% url 'index' %}" class="btn login_btn">Back to Shop</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>

var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Username..';
form_fields[2].placeholder='Email..';
form_fields[3].placeholder='Enter password...';
form_fields[4].placeholder='Re-enter Password...';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>
</body>
</html>
{% endblock %}